language: objective-c
osx_image: xcode9
podfile: SwiftyDequeuableExample/Podfile

before_script:
  - cd SwiftyDequeuableExample

script:
  - pod install
  - xcodebuild clean
  - xcodebuild build -workspace SwiftyDequeuableExample.xcworkspace -scheme SwiftyDequeuableExample -sdk iphonesimulator11.0 CODE_SIGNING_REQUIRED=NO
