language: objective-c
osx_image: xcode9
podfile: SwiftyDequeuableExample/Podfile

before_script:
  - cd SwiftyDequeuableExample

script:
  - pod install
  - xcodebuild clean
  - xcodebuild build -workspace SwiftyDequeuableExample.xcworkspace -scheme SwiftyDequeuableExample -sdk iphonesimulator11.0 CODE_SIGNING_REQUIRED=NO
  - xcodebuild test -workspace SwiftyDequeuableExample.xcworkspace -scheme SwiftyDequeuableExample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0' CODE_SIGNING_REQUIRED=NO
