language: objective-c
osx_image: xcode9
podfile: SwiftyDequeuableExample/Podfile

# Only create build on Pushes to Master or Pull Requests.
branches:
  only:
    - master

# Disable emails entirely
notifications:
  email: false

before_script:
  - cd SwiftyDequeuableExample

script:
  - pod install
  - xcodebuild clean
  - xcodebuild build -workspace SwiftyDequeuableExample.xcworkspace -scheme SwiftyDequeuableExample -sdk iphonesimulator11.0 CODE_SIGNING_REQUIRED=NO
  - xcodebuild test -workspace SwiftyDequeuableExample.xcworkspace -scheme SwiftyDequeuableExample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0' CODE_SIGNING_REQUIRED=NO
